services:
  app:
    build:
      context: .
      dockerfile: environment/app/Dockerfile
    container_name: parser-app
    restart: on-failure
    environment:
      MONGODB_HOST: ${MONGODB_HOST}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      SELENIUM_HOST: ${SELENIUM_HOST}
    depends_on:
      - mongo
      - mongo-express

  mongo:
    image: mongo:latest
    container_name: parser-db
    restart: on-failure
    ports:
      - "27017:27017"
    volumes:
      - ./environment/mongodb/data/:/data/db
    command: mongod --bind_ip_all
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

  mongo-express:
    image: mongo-express:latest
    container_name: parser-db-ui
    restart: on-failure
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASSWORD}
    depends_on:
      - mongo

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: parser-selenium
    restart: on-failure
    ports:
      - "4444:4444"
      - "7900:7900"
